version: '3'

services:
  router:
    image: router
    container_name: router
    restart: always
    network_mode: "host"
  
# docker-compose up -d

# docker run -d -v /var/run/docker.sock:/var/run/docker.sock --restart=always --name portainer --network web_bridge --ip 172.19.0.3 portainer/portainer

# docker network create --gateway 172.19.0.1 --subnet 172.19.0.0/16 web_bridge
