FROM openjdk:latest

ENTRYPOINT ["java","-jar","/source/sunbuntu.jar"]

#docker run -itd --restart always --name spring --network web_bridge --ip 172.19.0.100 -v /home/sunbuntu/shells/Dockerfiles/springboot:/source spring:0.0.1
