version: "3"
services:
  bitwarden:
    image: vaultwarden/server:latest
    restart: always
    environment:
      WEBSOCKET_ENABLED: 'true' # LiveSync 기능을 사용하기 위한 설정입니다.
      SIGNUPS_ALLOWED: 'true'   # 신규 가입을 허용할지에 대한 설정입니다.
    networks:
      web_bridge:
        ipv4_address: 172.19.0.13
      
networks:
  web_bridge:
    external: true
