version: '2.0'

# services
services:
  # guacd
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    restart: always
    networks:
      web_bridge:
        ipv4_address: 172.19.0.14

  # postgres
  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:13.4
    restart: always
    networks:
      web_bridge:
        ipv4_address: 172.19.0.15
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro

  # guacamole
  guacamole:
    container_name: guacamole_compose
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
      TOTP_ENABLED: "true"
    image: guacamole/guacamole
    links:
      - guacd
    networks:
      web_bridge:
        ipv4_address: 172.19.0.16
    expose:
      - 8080 # Guacamole is on :8080/guacamole, not /.
    restart: always
    
networks:
  web_bridge:
    external: true
