version: "2.1"
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - PASSWORD=PASSWORD
    restart: unless-stopped
    networks:
      web_bridge:
        ipv4_address: 172.19.0.12
      
networks:
  web_bridge:
    external: true
